spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers:
      - "localhost:9092"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cassandra:
    schema-action: none
    local-datacenter: datacenter1
    keyspace-name: tvmaze
    username: cassandra
    password: cassandra